version: '3.3'

services:
  # OpenTelemetry Collector
  otel_collector:
    image: 'otel/opentelemetry-collector-contrib:0.70.0'
    command: --config=/etc/otel-collector-config.yaml
      #user: root
    volumes:
      - ./confs/otel-collector-config.yaml:/etc/otel-collector-config.yaml
        # - ./certs/server.pem:/etc/tls/server.pem
        # - ./certs/server-key.pem:/etc/tls/server-key.pem
        # - ./certs/ca.pem:/etc/tls/ca.pem
        # - ./data/otel-logs:/var/log
    ports:
      - "4317:4317" # OTLP over gRPC receiver
      - "9464:9464" # Prometheus exporter
    depends_on:
      - prometheus
      #      - jaeger

        #  # Jaeger
        #  jaeger:
        #    image: jaegertracing/all-in-one:1.41.0
        #    ports:
        #      - "14250:14250" # Collector gRPC
        #      - "16686:16686" # Web HTTP

  # Prometheus
  prometheus:
    image: 'prom/prometheus:v2.23.0'
    command:
      - --config.file=/etc/prometheus/prometheus-config.yaml
    volumes:
      - ./confs/prometheus-config.yaml:/etc/prometheus/prometheus-config.yaml
    ports:
      - "9090:9090"

